# Numpy Arrays

In [1]:
import numpy as np

**Numpy come in 2 flavors**
- Vectors - One Dimensional
- Matrices - Two dimensional

### Creating Vectors from list

In [2]:
lst = list(range(6))
lst

[0, 1, 2, 3, 4, 5]

We can do that by using **`np.array()`**

In [3]:
arr = np.array(lst)
arr

array([0, 1, 2, 3, 4, 5])

### Creating a matrices from a list of list

In [4]:
lst1 = [[1,2,3],[4,5,6],[7,8,9]]
lst1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
mat = np.matrix(lst1)
mat

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
arr1 = np.array(lst1)

In [7]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr1.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

## Creating arrays using numpy functions

Following methods are used to create numpy arrays - `np.`
1. arange() - creates an array for a range of elements
2. zeros() - creates arrays of all zeros
3. ones() - creates arrays of all ones
4. linspace() - creates arrays of element between low, high and no of elements
5. eye() - creates Identity matrix of given size
---
Arrays with random numbers - `np.random.`
1. np.random.rand() - creates random no from unifrom distribution
2. np.random.randn() - creates random no form normal distribution
3. np.random.randint() - creates random no between 2 values

`np.arange()` function is similar to `range()` function for creating arrays

In [9]:
arr2 = np.arange(0,10)

In [10]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
len(arr2)

10

In [12]:
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
len(np.arange(1,13))

12

### Special functions to create arrays

**Arrays with all zeros** using `np.zeros(no_of_elements)`

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

**no of elements for the dimensions suing tuple for** `(rows, columns)`

In [15]:
# (row, column)
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### no of elements having all ones

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Linspace() - giving no of equal space

In [18]:
np.linspace(1,25,12)

array([ 1.        ,  3.18181818,  5.36363636,  7.54545455,  9.72727273,
       11.90909091, 14.09090909, 16.27272727, 18.45454545, 20.63636364,
       22.81818182, 25.        ])

In [19]:
np.linspace(0,100,23)

array([  0.        ,   4.54545455,   9.09090909,  13.63636364,
        18.18181818,  22.72727273,  27.27272727,  31.81818182,
        36.36363636,  40.90909091,  45.45454545,  50.        ,
        54.54545455,  59.09090909,  63.63636364,  68.18181818,
        72.72727273,  77.27272727,  81.81818182,  86.36363636,
        90.90909091,  95.45454545, 100.        ])

In [20]:
np.linspace(0,456, 20)

array([  0.,  24.,  48.,  72.,  96., 120., 144., 168., 192., 216., 240.,
       264., 288., 312., 336., 360., 384., 408., 432., 456.])

### Identity Matrix

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Arrays with Random Numbers

`np.random.rand( no_elements )` - is used to create random numbers between 0 and 1, these will be for **Uniform distribution**

In [23]:
np.random.rand(5)

array([0.04164554, 0.95151511, 0.93522449, 0.71022854, 0.53121234])

**creating a matrix by passing dimensions** - instead of tuple, we will be passing integers as `(row,column)`

In [24]:
np.random.rand(5,5)

array([[0.65981526, 0.65575103, 0.49472396, 0.50192532, 0.89189726],
       [0.01181788, 0.62422134, 0.1053099 , 0.36741852, 0.79929959],
       [0.25096684, 0.49521633, 0.56691522, 0.11713502, 0.43129826],
       [0.77668301, 0.46997106, 0.13350973, 0.45035315, 0.11636874],
       [0.04561234, 0.78267195, 0.49362471, 0.71121165, 0.46212181]])

In [25]:
np.random.rand(2,3)

array([[0.61492983, 0.99503099, 0.47352929],
       [0.4715483 , 0.93883128, 0.1476536 ]])

### Creating element for Normal Distribution

**Normal Distribution** is created by using `np.random.randn()`

In [26]:
np.random.randn(12)

array([-0.90864434, -0.64181895, -2.47424679,  1.17049206, -0.35598485,
       -0.70066784, -0.46224699, -0.72369476,  1.91831933,  0.02230339,
       -0.40596972, -0.97914526])

In [27]:
ts = np.random.randn(23)
ts

array([-0.17733723, -1.05048295,  0.76089902,  1.27770524, -0.34703808,
        0.21521157, -0.68258953, -0.18290323, -1.10778955, -1.24603875,
        1.01405029,  0.29903673,  0.81486748,  0.23316122, -0.59071551,
       -1.82650832,  0.08601504, -0.07120258,  0.5171072 ,  1.18946349,
        2.82296714,  0.14565303, -0.02689217])

In [28]:
np.random.randn(4,5)

array([[ 0.30064963,  0.41304233, -0.04568067,  0.21815479, -0.49703356],
       [ 1.02182744, -0.46705122,  0.18770475, -0.86769952, -1.4206182 ],
       [-1.45142932,  0.74773391,  1.17519437,  0.74805364, -0.49432168],
       [ 1.42110623,  1.19908982,  0.75616956,  1.9257238 ,  0.71577411]])

### randint() - to create random integers

`np.random.randint(low, high, size)`

In [29]:
np.random.randint(1,34,56)

array([20, 32, 19, 33, 22, 10, 11, 13,  8, 15, 19,  3,  6, 29, 16, 29, 30,
       33,  5, 22, 28, 11,  6, 22, 21, 28, 24, 31,  9, 25, 30,  3,  3, 27,
       18,  4, 23, 13, 10,  7, 13, 18, 17, 17, 15,  9, 32,  8,  8,  3, 22,
        3, 17,  9,  8,  1])

---

## Useful Methods of Arrays

**some of the Useful Methods of Arrays are**
1. reshape() - Changes the shape of array to new dimensions
2. min() - min value in array
3. max() - max value in array
4. argmax() - index of maximum value
5. argmin() - index of minimum value
---
Attributes:
1. shape - tells the shape of array
2. dtype - tells the datatype of an array

In [30]:
arr2 = np.arange(25)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

The original arrays does not gets affected, it has to be returned

In [31]:
arr2.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arint = np.random.randint(0,100,10)
arint

array([15, 98, 64, 24, 31, 86, 93, 73,  8, 49])

finding maximum value using `max()`

In [34]:
arr2.max()

24

In [35]:
arint.max()

98

finding minimum value using `min()`

In [36]:
arr2.min()

0

In [37]:
arint.min()

8

**finding index value of max and min using `argmax() and argmin()`**

In [38]:
arint

array([15, 98, 64, 24, 31, 86, 93, 73,  8, 49])

In [39]:
arint.max()

98

In [40]:
arint.argmax()

1

In [41]:
arint.min()

8

In [42]:
arint.argmin()

8

**finding the shape of array**

In [43]:
arr2.shape

(25,)

In [44]:
arint.shape

(10,)

In [45]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
# reshaping the array into 2 dimension matrix
ard = arr2.reshape(5,5)
ard

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
ard.shape

(5, 5)

In [48]:
arr2.shape

(25,)

**finding the data type of elements in an array using `dtype` attribute**

In [49]:
arr2.dtype

dtype('int32')

In [50]:
arint.dtype

dtype('int32')

In [51]:
arr.dtype

dtype('int32')

In [52]:
ts.dtype

dtype('float64')