# Array Indexing

Arrays are indexed from `0 to n-1` 
- for vectors we have to use only one dimension `[index of element]`
- for matrices we have to use `[row][column]`

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(0,101,10)
arr

array([38, 96, 21, 43, 54, 33, 50, 56,  9, 54])

The indexing concept is same to that of Python List

In [3]:
arr1 = np.arange(0,11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In this example, index number and element values are same

In [4]:
arr1[0]

0

In [5]:
arr1[5]

5

In [6]:
arr

array([38, 96, 21, 43, 54, 33, 50, 56,  9, 54])

In [7]:
# 6th element
arr[5]

33

In [8]:
# 10th element
arr[9]

54

In [9]:
len(arr)

10

### Using slice

In [10]:
arr[:4]

array([38, 96, 21, 43])

In [11]:
arr[2:6]

array([21, 43, 54, 33])

In [12]:
arr[6:]

array([50, 56,  9, 54])

In [13]:
arr1[:5]

array([0, 1, 2, 3, 4])

In [14]:
arr1[5:]

array([ 5,  6,  7,  8,  9, 10])

### using negative indexing

In [15]:
arr[-5:]

array([33, 50, 56,  9, 54])

In [16]:
arr[:-5]

array([38, 96, 21, 43, 54])

In [17]:
arr1[-5:]

array([ 6,  7,  8,  9, 10])

In [18]:
arr1[:-5]

array([0, 1, 2, 3, 4, 5])

Array differs from Lists as they can **broadcast the values** i.e take several values at same time. `[:5] = value`

In [19]:
arr

array([38, 96, 21, 43, 54, 33, 50, 56,  9, 54])

In [20]:
arr[:5] = 100

In [21]:
arr

array([100, 100, 100, 100, 100,  33,  50,  56,   9,  54])

In [22]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

When slicing is done in order to copy an array, it is **only a reference**

In [23]:
# broadcasting slice of an array
slc = arr1[:5]
slc

array([0, 1, 2, 3, 4])

In [24]:
slc[: ]= 100
slc

array([100, 100, 100, 100, 100])

The original value is also affected as it is only a reference and not a copy

In [25]:
arr1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

changing values of arr1 to original

In [26]:
arr1 = np.arange(0,11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Creating copy of arrays

Array copy can be created using **`[:].copy`** `"slice and copy"`

In [27]:
arr2 = arr1[:5].copy()
arr2

array([0, 1, 2, 3, 4])

In [28]:
arr2[:] = 5

In [29]:
arr2

array([5, 5, 5, 5, 5])

In [30]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

---

# Matrices

In [31]:
mat1 = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
mat1

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
mat1.shape

(3, 3)

In [33]:
mat1.dtype

dtype('int32')

## Indexing in 2D Arrays

There are 2 formats for indexing in 2D arrays
1. Double bracket format - `Array[row][column]`
2. Single Bracket format - `Array[row, Column]`

### Double Bracket Format

In [34]:
mat1

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

fetching value 5 

In [35]:
mat1[0][0]

5

Fetching 35 value

In [36]:
mat1[2][0]

35

### indexing whole row

In [37]:
# indexing whole row
mat1[0]

array([ 5, 10, 15])

In [38]:
mat1[1]

array([20, 25, 30])

In [39]:
mat1[2]

array([35, 40, 45])

## Using one bracket indexing

### Indexing whole column

In [40]:
mat1

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [41]:
mat1[:,0]

array([ 5, 20, 35])

In [42]:
mat1[:,1]

array([10, 25, 40])

In [43]:
mat1[:,2]

array([15, 30, 45])

### indexing only some rows and columns

In [44]:
mat1

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

fetch 1 and 3 rows of all columns

In [45]:
mat1[[0,2], :]

array([[ 5, 10, 15],
       [35, 40, 45]])

Fetch 1, 3 row and 2,3 column
- we have to fetch the row first and from resultant matrix we have to apply another selection of column
- if we try to use the same syntax then only elements will be extracted

In [46]:
mat1[[0,2], :][:, [1,2]]

array([[10, 15],
       [40, 45]])

In [47]:
mat1[[0,2], [1,2]]

array([10, 45])

The above syntax is equal to saying
`mat1[0][1] and mat1[2][2]` and it only maps elements

# Conditional selection

In [48]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

We can compare all the elements of array by using conditional operators on `array name`

In [49]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

This gives us an opportunity to see only those numbers which satisfy certain condition **if we put them in the square brackets**

In [50]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [51]:
arr[arr<=3]

array([1, 2, 3])

### matrices conditionals

In [52]:
mat2 = np.random.randint(0,101,50).reshape(5,10)
mat2

array([[38, 81,  0, 86, 35, 66, 18, 74, 33, 34],
       [90, 40, 24, 54,  2, 41, 64, 26, 76, 93],
       [26, 55,  3, 35, 79, 74, 51, 11, 91, 73],
       [72, 68, 67, 74, 56, 70, 65, 24, 40, 76],
       [13,  6, 96, 96, 44, 47, 95, 19,  9, 12]])

In [53]:
mat2.shape

(5, 10)

In [54]:
mat2.dtype

dtype('int32')

In [55]:
mat2[1:3, 3:5]

array([[54,  2],
       [35, 79]])

---

# Numpy Operations

There are basically 3 type of operations:
1. Array with Array operations
2. Array with Scalar operations
3. Universal Array Functions

In [56]:
ar = np.arange(11)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 1. Array with Array operations

Using simple mathematics operators like `+, -, *, /`. **Both the arrays should be of same size**

In [57]:
ar + ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [58]:
ar1 = np.random.randint(0,100, 11)
ar1

array([ 5, 10, 76, 72, 70, 25,  6, 41, 71, 54, 80])

In [59]:
ar + ar1

array([ 5, 11, 78, 75, 74, 30, 12, 48, 79, 63, 90])

In [60]:
# subtraction
ar1 - ar

array([ 5,  9, 74, 69, 66, 20,  0, 34, 63, 45, 70])

In [61]:
# subtraction
ar - ar1

array([ -5,  -9, -74, -69, -66, -20,   0, -34, -63, -45, -70])

In [62]:
# Multiplication
ar1 * ar

array([  0,  10, 152, 216, 280, 125,  36, 287, 568, 486, 800])

Make sure there is no problem of **divide by zero**

In [63]:
# division
ar/ar1

array([0.        , 0.1       , 0.02631579, 0.04166667, 0.05714286,
       0.2       , 1.        , 0.17073171, 0.11267606, 0.16666667,
       0.125     ])

In [64]:
# modulus
ar % ar1

array([ 0,  1,  2,  3,  4,  5,  0,  7,  8,  9, 10], dtype=int32)

In [65]:
#modulus
ar1[1:] % ar[1:]

array([0, 0, 0, 2, 0, 0, 6, 7, 0, 0], dtype=int32)

## 2. Array with Scalar Operations

Scalar operations are done on every single element of array

In [66]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
ar + 234

array([234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244])

In [68]:
ar * 12

array([  0,  12,  24,  36,  48,  60,  72,  84,  96, 108, 120])

In [69]:
ar /12

array([0.        , 0.08333333, 0.16666667, 0.25      , 0.33333333,
       0.41666667, 0.5       , 0.58333333, 0.66666667, 0.75      ,
       0.83333333])

In [70]:
ar**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [71]:
ar/ar

C:\Users\Anil\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [72]:
(ar/ar).dtype

C:\Users\Anil\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


dtype('float64')

## 3. Universal Array Functions

These are the functions associated with arrays and they can be accessed by **`using np.function_name(array)`**
- np.sqrt() - square root of array
- np.exp() - exponential of array
- np.sin() - sine of array

> [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html) here there are list of universal functions or Ufunc

In [73]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
# taking square root of array
np.sqrt(ar)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [75]:
# taking exponential of array elements
np.exp(ar)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [76]:
np.sin(ar)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [77]:
# finding log of arr
np.log(ar)

C:\Users\Anil\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])